---
abstract: 'Perl extension for Test Double.'
author:
  - 'NAKAGAWA Masaki <masaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Flatten: 0
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Double
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Monadic: 0
  Exporter: 0
  Scalar::Util: 1.14
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/masaki/Test-Double.git
version: 0.03
